export type MenuSeedProduct = {
  id: string
  sourceNumber: number
  section: string
  category: string
  name: string
  description: string
  price: number
  imageKind: string
  available: boolean
  sortOrder: number
}

export const menuSeedProducts: MenuSeedProduct[] = [
  {
    "id": "producto-001",
    "sourceNumber": 1,
    "section": "Carta de Adultos",
    "category": "Hot Cakes",
    "name": "Hot Cakes",
    "description": "Hot Cakes",
    "price": 80,
    "imageKind": "hotcakes",
    "available": true,
    "sortOrder": 1
  },
  {
    "id": "producto-002",
    "sourceNumber": 2,
    "section": "Carta de Adultos",
    "category": "Pan",
    "name": "Pan de Dulce",
    "description": "Pan",
    "price": 25,
    "imageKind": "bread",
    "available": true,
    "sortOrder": 2
  },
  {
    "id": "producto-003",
    "sourceNumber": 3,
    "section": "Carta de Adultos",
    "category": "Sandwiches",
    "name": "Jamón",
    "description": "Sandwiches",
    "price": 30,
    "imageKind": "sandwich",
    "available": true,
    "sortOrder": 3
  },
  {
    "id": "producto-004",
    "sourceNumber": 4,
    "section": "Carta de Adultos",
    "category": "Sandwiches",
    "name": "Huevo",
    "description": "Sandwiches",
    "price": 30,
    "imageKind": "sandwich",
    "available": true,
    "sortOrder": 4
  },
  {
    "id": "producto-005",
    "sourceNumber": 5,
    "section": "Carta de Adultos",
    "category": "Sandwiches",
    "name": "Pechuga de Pavo",
    "description": "Sandwiches",
    "price": 40,
    "imageKind": "sandwich",
    "available": true,
    "sortOrder": 5
  },
  {
    "id": "producto-006",
    "sourceNumber": 6,
    "section": "Carta de Adultos",
    "category": "Sandwiches",
    "name": "Ensalada Rusa con Pollo",
    "description": "Sandwiches",
    "price": 40,
    "imageKind": "sandwich",
    "available": true,
    "sortOrder": 6
  },
  {
    "id": "producto-007",
    "sourceNumber": 7,
    "section": "Carta de Adultos",
    "category": "Sandwiches",
    "name": "Ensalada Rusa con Atún",
    "description": "Sandwiches",
    "price": 40,
    "imageKind": "sandwich",
    "available": true,
    "sortOrder": 7
  },
  {
    "id": "producto-008",
    "sourceNumber": 8,
    "section": "Carta de Adultos",
    "category": "Sandwiches",
    "name": "Pechuga Empanizada",
    "description": "Sandwiches",
    "price": 50,
    "imageKind": "sandwich",
    "available": true,
    "sortOrder": 8
  },
  {
    "id": "producto-009",
    "sourceNumber": 9,
    "section": "Carta de Adultos",
    "category": "Tacos",
    "name": "Suadero de Res",
    "description": "Tacos",
    "price": 40,
    "imageKind": "tacos",
    "available": true,
    "sortOrder": 9
  },
  {
    "id": "producto-010",
    "sourceNumber": 10,
    "section": "Carta de Adultos",
    "category": "Tacos",
    "name": "Tacos de Birria",
    "description": "Tacos",
    "price": 40,
    "imageKind": "tacos",
    "available": true,
    "sortOrder": 10
  },
  {
    "id": "producto-011",
    "sourceNumber": 11,
    "section": "Carta de Adultos",
    "category": "Tacos",
    "name": "Pastor",
    "description": "Tacos",
    "price": 35,
    "imageKind": "tacos",
    "available": true,
    "sortOrder": 11
  },
  {
    "id": "producto-012",
    "sourceNumber": 12,
    "section": "Carta de Adultos",
    "category": "Tacos",
    "name": "Chorizo",
    "description": "Tacos",
    "price": 25,
    "imageKind": "tacos",
    "available": true,
    "sortOrder": 12
  },
  {
    "id": "producto-013",
    "sourceNumber": 13,
    "section": "Carta de Adultos",
    "category": "Tacos",
    "name": "Campechanos",
    "description": "Tacos",
    "price": 35,
    "imageKind": "tacos",
    "available": true,
    "sortOrder": 13
  },
  {
    "id": "producto-014",
    "sourceNumber": 14,
    "section": "Carta de Adultos",
    "category": "Tacos",
    "name": "Tacos Dorados de Pollo",
    "description": "Tacos",
    "price": 80,
    "imageKind": "tacos",
    "available": true,
    "sortOrder": 14
  },
  {
    "id": "producto-015",
    "sourceNumber": 15,
    "section": "Carta de Adultos",
    "category": "Tortas",
    "name": "Milanesa de Res",
    "description": "Tortas",
    "price": 80,
    "imageKind": "sandwich",
    "available": true,
    "sortOrder": 15
  },
  {
    "id": "producto-016",
    "sourceNumber": 16,
    "section": "Carta de Adultos",
    "category": "Tortas",
    "name": "Milanesa de Puerco",
    "description": "Tortas",
    "price": 65,
    "imageKind": "sandwich",
    "available": true,
    "sortOrder": 16
  },
  {
    "id": "producto-017",
    "sourceNumber": 17,
    "section": "Carta de Adultos",
    "category": "Tortas",
    "name": "Pierna Espanola",
    "description": "Tortas",
    "price": 65,
    "imageKind": "sandwich",
    "available": true,
    "sortOrder": 17
  },
  {
    "id": "producto-018",
    "sourceNumber": 18,
    "section": "Carta de Adultos",
    "category": "Tortas",
    "name": "Pechuga Empanizada",
    "description": "Tortas",
    "price": 65,
    "imageKind": "sandwich",
    "available": true,
    "sortOrder": 18
  },
  {
    "id": "producto-019",
    "sourceNumber": 19,
    "section": "Carta de Adultos",
    "category": "Tortas",
    "name": "Cubana",
    "description": "Tortas",
    "price": 90,
    "imageKind": "sandwich",
    "available": true,
    "sortOrder": 19
  },
  {
    "id": "producto-020",
    "sourceNumber": 20,
    "section": "Carta de Adultos",
    "category": "Garnachas",
    "name": "Quesadilla de tinga",
    "description": "Garnachas",
    "price": 40,
    "imageKind": "garnachas",
    "available": true,
    "sortOrder": 20
  },
  {
    "id": "producto-021",
    "sourceNumber": 21,
    "section": "Carta de Adultos",
    "category": "Garnachas",
    "name": "Quesadilla de Flor de Calabaza",
    "description": "Garnachas",
    "price": 40,
    "imageKind": "garnachas",
    "available": true,
    "sortOrder": 21
  },
  {
    "id": "producto-022",
    "sourceNumber": 22,
    "section": "Carta de Adultos",
    "category": "Garnachas",
    "name": "Quesadilla de Chicharron Prensado",
    "description": "Garnachas",
    "price": 40,
    "imageKind": "garnachas",
    "available": true,
    "sortOrder": 22
  },
  {
    "id": "producto-023",
    "sourceNumber": 23,
    "section": "Carta de Adultos",
    "category": "Garnachas",
    "name": "Quesadilla de Queso Oaxaca",
    "description": "Garnachas",
    "price": 40,
    "imageKind": "garnachas",
    "available": true,
    "sortOrder": 23
  },
  {
    "id": "producto-024",
    "sourceNumber": 24,
    "section": "Carta de Adultos",
    "category": "Garnachas",
    "name": "Gorditas de Carnitas",
    "description": "Garnachas",
    "price": 50,
    "imageKind": "garnachas",
    "available": true,
    "sortOrder": 24
  },
  {
    "id": "producto-025",
    "sourceNumber": 25,
    "section": "Carta de Adultos",
    "category": "Garnachas",
    "name": "Gorditas de Chicharron Prensado",
    "description": "Garnachas",
    "price": 40,
    "imageKind": "garnachas",
    "available": true,
    "sortOrder": 25
  },
  {
    "id": "producto-026",
    "sourceNumber": 26,
    "section": "Carta de Adultos",
    "category": "Garnachas",
    "name": "Gorditas de Suadero",
    "description": "Garnachas",
    "price": 50,
    "imageKind": "garnachas",
    "available": true,
    "sortOrder": 26
  },
  {
    "id": "producto-027",
    "sourceNumber": 27,
    "section": "Carta de Adultos",
    "category": "Garnachas",
    "name": "Sopes de Bistec",
    "description": "Garnachas",
    "price": 40,
    "imageKind": "garnachas",
    "available": true,
    "sortOrder": 27
  },
  {
    "id": "producto-028",
    "sourceNumber": 28,
    "section": "Carta de Adultos",
    "category": "Garnachas",
    "name": "Sopes de Suadero",
    "description": "Garnachas",
    "price": 40,
    "imageKind": "garnachas",
    "available": true,
    "sortOrder": 28
  },
  {
    "id": "producto-029",
    "sourceNumber": 29,
    "section": "Carta de Adultos",
    "category": "Garnachas",
    "name": "Huaraches de Bistec",
    "description": "Garnachas",
    "price": 70,
    "imageKind": "garnachas",
    "available": true,
    "sortOrder": 29
  },
  {
    "id": "producto-030",
    "sourceNumber": 30,
    "section": "Carta de Adultos",
    "category": "Garnachas",
    "name": "Tlacoyos",
    "description": "Garnachas",
    "price": 30,
    "imageKind": "garnachas",
    "available": true,
    "sortOrder": 30
  },
  {
    "id": "producto-031",
    "sourceNumber": 31,
    "section": "Carta de Adultos",
    "category": "Chilaquiles",
    "name": "Huevos Estrellados",
    "description": "Chilaquiles · Verdes o Rojos",
    "price": 50,
    "imageKind": "chilaquiles",
    "available": true,
    "sortOrder": 31
  },
  {
    "id": "producto-032",
    "sourceNumber": 32,
    "section": "Carta de Adultos",
    "category": "Chilaquiles",
    "name": "Huevos Revueltos",
    "description": "Chilaquiles · Verdes o Rojos",
    "price": 50,
    "imageKind": "chilaquiles",
    "available": true,
    "sortOrder": 32
  },
  {
    "id": "producto-033",
    "sourceNumber": 33,
    "section": "Carta de Adultos",
    "category": "Chilaquiles",
    "name": "Pollo",
    "description": "Chilaquiles · Verdes o Rojos",
    "price": 60,
    "imageKind": "chilaquiles",
    "available": true,
    "sortOrder": 33
  },
  {
    "id": "producto-034",
    "sourceNumber": 34,
    "section": "Carta de Adultos",
    "category": "Chilaquiles",
    "name": "Bistec de Puerco",
    "description": "Chilaquiles · Verdes o Rojos",
    "price": 80,
    "imageKind": "chilaquiles",
    "available": true,
    "sortOrder": 34
  },
  {
    "id": "producto-035",
    "sourceNumber": 35,
    "section": "Carta de Adultos",
    "category": "Chilaquiles",
    "name": "Bistec de Res",
    "description": "Chilaquiles · Verdes o Rojos",
    "price": 80,
    "imageKind": "chilaquiles",
    "available": true,
    "sortOrder": 35
  },
  {
    "id": "producto-036",
    "sourceNumber": 36,
    "section": "Carta de Adultos",
    "category": "Enchiladas",
    "name": "Pollo",
    "description": "Enchiladas · Verdes o Rojos",
    "price": 80,
    "imageKind": "enchiladas",
    "available": true,
    "sortOrder": 36
  },
  {
    "id": "producto-037",
    "sourceNumber": 37,
    "section": "Carta de Adultos",
    "category": "Enchiladas",
    "name": "Pollo",
    "description": "Enchiladas · Suizas Verdes o Rojas",
    "price": 90,
    "imageKind": "enchiladas",
    "available": true,
    "sortOrder": 37
  },
  {
    "id": "producto-038",
    "sourceNumber": 38,
    "section": "Carta de Adultos",
    "category": "Huevos",
    "name": "Divorciados",
    "description": "Huevos",
    "price": 50,
    "imageKind": "eggs",
    "available": true,
    "sortOrder": 38
  },
  {
    "id": "producto-039",
    "sourceNumber": 39,
    "section": "Carta de Adultos",
    "category": "Huevos",
    "name": "Al Albañil",
    "description": "Huevos",
    "price": 50,
    "imageKind": "eggs",
    "available": true,
    "sortOrder": 39
  },
  {
    "id": "producto-040",
    "sourceNumber": 40,
    "section": "Carta de Adultos",
    "category": "Huevos",
    "name": "A la Mexicana",
    "description": "Huevos",
    "price": 60,
    "imageKind": "eggs",
    "available": true,
    "sortOrder": 40
  },
  {
    "id": "producto-041",
    "sourceNumber": 41,
    "section": "Carta de Adultos",
    "category": "Huevos",
    "name": "Con Jamón",
    "description": "Huevos",
    "price": 50,
    "imageKind": "eggs",
    "available": true,
    "sortOrder": 41
  },
  {
    "id": "producto-042",
    "sourceNumber": 42,
    "section": "Carta de Adultos",
    "category": "Huevos",
    "name": "Con Salchicha",
    "description": "Huevos",
    "price": 50,
    "imageKind": "eggs",
    "available": true,
    "sortOrder": 42
  },
  {
    "id": "producto-043",
    "sourceNumber": 43,
    "section": "Carta de Adultos",
    "category": "Huevos",
    "name": "Con Chorizo",
    "description": "Huevos",
    "price": 50,
    "imageKind": "eggs",
    "available": true,
    "sortOrder": 43
  },
  {
    "id": "producto-044",
    "sourceNumber": 44,
    "section": "Carta de Adultos",
    "category": "Carnes",
    "name": "Arrachera",
    "description": "Carnes",
    "price": 100,
    "imageKind": "meat",
    "available": true,
    "sortOrder": 44
  },
  {
    "id": "producto-045",
    "sourceNumber": 45,
    "section": "Carta de Adultos",
    "category": "Carnes",
    "name": "Bistec de Res Asado",
    "description": "Carnes",
    "price": 100,
    "imageKind": "meat",
    "available": true,
    "sortOrder": 45
  },
  {
    "id": "producto-046",
    "sourceNumber": 46,
    "section": "Carta de Adultos",
    "category": "Carnes",
    "name": "Cecina",
    "description": "Carnes",
    "price": 90,
    "imageKind": "meat",
    "available": true,
    "sortOrder": 46
  },
  {
    "id": "producto-047",
    "sourceNumber": 47,
    "section": "Carta de Adultos",
    "category": "Carnes",
    "name": "Bistec de Puerco Asado",
    "description": "Carnes",
    "price": 80,
    "imageKind": "meat",
    "available": true,
    "sortOrder": 47
  },
  {
    "id": "producto-048",
    "sourceNumber": 48,
    "section": "Carta de Adultos",
    "category": "Carnes",
    "name": "Milanesa de Res",
    "description": "Carnes",
    "price": 100,
    "imageKind": "meat",
    "available": true,
    "sortOrder": 48
  },
  {
    "id": "producto-049",
    "sourceNumber": 49,
    "section": "Carta de Adultos",
    "category": "Carnes",
    "name": "Milanesa de Puerco",
    "description": "Carnes",
    "price": 90,
    "imageKind": "meat",
    "available": true,
    "sortOrder": 49
  },
  {
    "id": "producto-050",
    "sourceNumber": 50,
    "section": "Carta de Adultos",
    "category": "Carnes",
    "name": "Pechuga Empanizada",
    "description": "Carnes",
    "price": 85,
    "imageKind": "meat",
    "available": true,
    "sortOrder": 50
  },
  {
    "id": "producto-051",
    "sourceNumber": 51,
    "section": "Carta de Adultos",
    "category": "Carnes",
    "name": "Pechuga Asada",
    "description": "Carnes",
    "price": 85,
    "imageKind": "meat",
    "available": true,
    "sortOrder": 51
  },
  {
    "id": "producto-052",
    "sourceNumber": 52,
    "section": "Carta de Adultos",
    "category": "Ensaladas",
    "name": "Ensalada Italiana",
    "description": "Ensaladas",
    "price": 70,
    "imageKind": "salad",
    "available": true,
    "sortOrder": 52
  },
  {
    "id": "producto-053",
    "sourceNumber": 53,
    "section": "Carta de Adultos",
    "category": "Ensaladas",
    "name": "Ensalada de Verduras al Vapor",
    "description": "Ensaladas",
    "price": 70,
    "imageKind": "salad",
    "available": true,
    "sortOrder": 53
  },
  {
    "id": "producto-054",
    "sourceNumber": 54,
    "section": "Carta de Adultos",
    "category": "Ensaladas",
    "name": "Ensalada de Frutos Rojos",
    "description": "Ensaladas",
    "price": 80,
    "imageKind": "salad",
    "available": true,
    "sortOrder": 54
  },
  {
    "id": "producto-055",
    "sourceNumber": 55,
    "section": "Carta de Adultos",
    "category": "Ensaladas",
    "name": "Ensalada de Frutas",
    "description": "Ensaladas",
    "price": 80,
    "imageKind": "salad",
    "available": true,
    "sortOrder": 55
  },
  {
    "id": "producto-056",
    "sourceNumber": 56,
    "section": "Carta de Adultos",
    "category": "Guisados",
    "name": "Pollo En Adobo Con Papas",
    "description": "Guisados",
    "price": 60,
    "imageKind": "guisado",
    "available": true,
    "sortOrder": 56
  },
  {
    "id": "producto-057",
    "sourceNumber": 57,
    "section": "Carta de Adultos",
    "category": "Guisados",
    "name": "Muslos Asados Con Spaghetti y Ensalada",
    "description": "Guisados",
    "price": 80,
    "imageKind": "salad",
    "available": true,
    "sortOrder": 57
  },
  {
    "id": "producto-058",
    "sourceNumber": 58,
    "section": "Carta de Adultos",
    "category": "Guisados",
    "name": "Pollo a la Jardinera",
    "description": "Guisados",
    "price": 70,
    "imageKind": "guisado",
    "available": true,
    "sortOrder": 58
  },
  {
    "id": "producto-059",
    "sourceNumber": 59,
    "section": "Carta de Adultos",
    "category": "Guisados",
    "name": "Pollo En Chile Pasilla",
    "description": "Guisados",
    "price": 80,
    "imageKind": "guisado",
    "available": true,
    "sortOrder": 59
  },
  {
    "id": "producto-060",
    "sourceNumber": 60,
    "section": "Carta de Adultos",
    "category": "Guisados",
    "name": "Carne de Puerco en Chile Verde con Nopales",
    "description": "Guisados",
    "price": 70,
    "imageKind": "meat",
    "available": true,
    "sortOrder": 60
  },
  {
    "id": "producto-061",
    "sourceNumber": 61,
    "section": "Carta de Adultos",
    "category": "Guisados",
    "name": "Salchichas a la Mexicana",
    "description": "Guisados",
    "price": 60,
    "imageKind": "guisado",
    "available": true,
    "sortOrder": 61
  },
  {
    "id": "producto-062",
    "sourceNumber": 62,
    "section": "Carta de Adultos",
    "category": "Chiles Rellenos",
    "name": "Chiles Rellenos de Queso Oaxaca",
    "description": "Chiles Rellenos",
    "price": 90,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 62
  },
  {
    "id": "producto-063",
    "sourceNumber": 63,
    "section": "Carta de Adultos",
    "category": "Chiles Rellenos",
    "name": "Chiles Rellenos de Queso Canasto",
    "description": "Chiles Rellenos",
    "price": 90,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 63
  },
  {
    "id": "producto-064",
    "sourceNumber": 64,
    "section": "Carta de Adultos",
    "category": "Chiles Rellenos",
    "name": "Chiles Rellenos de Atún",
    "description": "Chiles Rellenos",
    "price": 100,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 64
  },
  {
    "id": "producto-065",
    "sourceNumber": 65,
    "section": "Carta de Adultos",
    "category": "Viernes, Sabado y Domingo",
    "name": "Caldo de Camarón",
    "description": "Viernes, Sabado y Domingo",
    "price": 100,
    "imageKind": "seafood",
    "available": true,
    "sortOrder": 65
  },
  {
    "id": "producto-066",
    "sourceNumber": 66,
    "section": "Carta de Adultos",
    "category": "Viernes, Sabado y Domingo",
    "name": "Camarones al Mojo de Ajo",
    "description": "Viernes, Sabado y Domingo",
    "price": 200,
    "imageKind": "seafood",
    "available": true,
    "sortOrder": 66
  },
  {
    "id": "producto-067",
    "sourceNumber": 67,
    "section": "Carta de Adultos",
    "category": "Viernes, Sabado y Domingo",
    "name": "Cóctel de Camarón",
    "description": "Viernes, Sabado y Domingo",
    "price": 150,
    "imageKind": "seafood",
    "available": true,
    "sortOrder": 67
  },
  {
    "id": "producto-068",
    "sourceNumber": 68,
    "section": "Carta de Adultos",
    "category": "Viernes, Sabado y Domingo",
    "name": "Camarones Aguachiles",
    "description": "Viernes, Sabado y Domingo",
    "price": 200,
    "imageKind": "seafood",
    "available": true,
    "sortOrder": 68
  },
  {
    "id": "producto-069",
    "sourceNumber": 69,
    "section": "Carta de Adultos",
    "category": "Viernes, Sabado y Domingo",
    "name": "Empanadas de Camáron",
    "description": "Viernes, Sabado y Domingo",
    "price": 70,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 69
  },
  {
    "id": "producto-070",
    "sourceNumber": 70,
    "section": "Carta de Adultos",
    "category": "Viernes, Sabado y Domingo",
    "name": "Tostada de Camarón",
    "description": "Viernes, Sabado y Domingo",
    "price": 100,
    "imageKind": "seafood",
    "available": true,
    "sortOrder": 70
  },
  {
    "id": "producto-071",
    "sourceNumber": 71,
    "section": "Carta de Adultos",
    "category": "Viernes, Sabado y Domingo",
    "name": "Mojarra al Mojo de Ajo",
    "description": "Viernes, Sabado y Domingo",
    "price": 200,
    "imageKind": "seafood",
    "available": true,
    "sortOrder": 71
  },
  {
    "id": "producto-072",
    "sourceNumber": 72,
    "section": "Carta de Adultos",
    "category": "Viernes, Sabado y Domingo",
    "name": "Filetitos",
    "description": "Viernes, Sabado y Domingo",
    "price": 200,
    "imageKind": "seafood",
    "available": true,
    "sortOrder": 72
  },
  {
    "id": "producto-073",
    "sourceNumber": 73,
    "section": "Carta de Adultos",
    "category": "Viernes, Sabado y Domingo",
    "name": "Birria",
    "description": "Viernes, Sabado y Domingo",
    "price": 100,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 73
  },
  {
    "id": "producto-074",
    "sourceNumber": 74,
    "section": "Carta de Adultos",
    "category": "Viernes, Sabado y Domingo",
    "name": "Pozole",
    "description": "Viernes, Sabado y Domingo",
    "price": 90,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 74
  },
  {
    "id": "producto-075",
    "sourceNumber": 75,
    "section": "Carta de Adultos",
    "category": "Viernes, Sabado y Domingo",
    "name": "Pancita",
    "description": "Viernes, Sabado y Domingo",
    "price": 90,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 75
  },
  {
    "id": "producto-076",
    "sourceNumber": 76,
    "section": "Carta de Adultos",
    "category": "Hamburguesas",
    "name": "Hamburguesa De Arrachera Hawaiana Con Papas",
    "description": "Hamburguesas",
    "price": 75,
    "imageKind": "meat",
    "available": true,
    "sortOrder": 76
  },
  {
    "id": "producto-077",
    "sourceNumber": 77,
    "section": "Carta de Adultos",
    "category": "Hamburguesas",
    "name": "Hamburguesa De Arrachera Doble Carne Hawaiana Con Papas",
    "description": "Hamburguesas",
    "price": 95,
    "imageKind": "meat",
    "available": true,
    "sortOrder": 77
  },
  {
    "id": "producto-078",
    "sourceNumber": 78,
    "section": "Carta de Niños",
    "category": "Combo Kids 1",
    "name": "Combo Kids 1",
    "description": "Méxicano",
    "price": 50,
    "imageKind": "kids",
    "available": true,
    "sortOrder": 78
  },
  {
    "id": "producto-079",
    "sourceNumber": 79,
    "section": "Carta de Niños",
    "category": "Combo Kids 2",
    "name": "Combo Kids 2",
    "description": "Americano",
    "price": 70,
    "imageKind": "kids",
    "available": true,
    "sortOrder": 79
  },
  {
    "id": "producto-080",
    "sourceNumber": 80,
    "section": "Carta de Niños",
    "category": "Combo Kids 3",
    "name": "Combo Kids 3",
    "description": "Español",
    "price": 80,
    "imageKind": "kids",
    "available": true,
    "sortOrder": 80
  },
  {
    "id": "producto-081",
    "sourceNumber": 81,
    "section": "Carta de Niños",
    "category": "Combo Kids 4",
    "name": "Combo Kids 4",
    "description": "Chino",
    "price": 90,
    "imageKind": "kids",
    "available": true,
    "sortOrder": 81
  },
  {
    "id": "producto-082",
    "sourceNumber": 82,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Americano",
    "description": "Bebidas · Café",
    "price": 15,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 82
  },
  {
    "id": "producto-083",
    "sourceNumber": 83,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Expresso",
    "description": "Bebidas · Café",
    "price": 25,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 83
  },
  {
    "id": "producto-084",
    "sourceNumber": 84,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Nescafé",
    "description": "Bebidas · Café",
    "price": 25,
    "imageKind": "coffee",
    "available": true,
    "sortOrder": 84
  },
  {
    "id": "producto-085",
    "sourceNumber": 85,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Manzanilla",
    "description": "Bebidas · Te",
    "price": 20,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 85
  },
  {
    "id": "producto-086",
    "sourceNumber": 86,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Limón",
    "description": "Bebidas · Te",
    "price": 20,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 86
  },
  {
    "id": "producto-087",
    "sourceNumber": 87,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Canela",
    "description": "Bebidas · Te",
    "price": 20,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 87
  },
  {
    "id": "producto-088",
    "sourceNumber": 88,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Chocolate Abuelita",
    "description": "Bebidas · Chocolate",
    "price": 30,
    "imageKind": "chocolate",
    "available": true,
    "sortOrder": 88
  },
  {
    "id": "producto-089",
    "sourceNumber": 89,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Fresa",
    "description": "Bebidas · Licuados",
    "price": 50,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 89
  },
  {
    "id": "producto-090",
    "sourceNumber": 90,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Plátano",
    "description": "Bebidas · Licuados",
    "price": 50,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 90
  },
  {
    "id": "producto-091",
    "sourceNumber": 91,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Guayaba",
    "description": "Bebidas · Licuados",
    "price": 50,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 91
  },
  {
    "id": "producto-092",
    "sourceNumber": 92,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Mango",
    "description": "Bebidas · Licuados",
    "price": 50,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 92
  },
  {
    "id": "producto-093",
    "sourceNumber": 93,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Chocolate",
    "description": "Bebidas · Licuados",
    "price": 50,
    "imageKind": "chocolate",
    "available": true,
    "sortOrder": 93
  },
  {
    "id": "producto-094",
    "sourceNumber": 94,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Coca de Vidrio",
    "description": "Bebidas · Refresco",
    "price": 15,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 94
  },
  {
    "id": "producto-095",
    "sourceNumber": 95,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Lata de Coca",
    "description": "Bebidas · Refresco",
    "price": 35,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 95
  },
  {
    "id": "producto-096",
    "sourceNumber": 96,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Jugo del Valle Guayaba",
    "description": "Bebidas · Refresco",
    "price": 15,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 96
  },
  {
    "id": "producto-097",
    "sourceNumber": 97,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Jugo del Valle Mango",
    "description": "Bebidas · Refresco",
    "price": 15,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 97
  },
  {
    "id": "producto-098",
    "sourceNumber": 98,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Tehuacan Preparado",
    "description": "Bebidas · Refresco",
    "price": 25,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 98
  },
  {
    "id": "producto-099",
    "sourceNumber": 99,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Naranjada",
    "description": "Bebidas · Refresco",
    "price": 30,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 99
  },
  {
    "id": "producto-100",
    "sourceNumber": 100,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Limónada",
    "description": "Bebidas · Refresco",
    "price": 30,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 100
  },
  {
    "id": "producto-101",
    "sourceNumber": 101,
    "section": "Carta de Bebidas",
    "category": "Bebidas",
    "name": "Sangría Preparada",
    "description": "Bebidas · Refresco",
    "price": 35,
    "imageKind": "restaurant",
    "available": true,
    "sortOrder": 101
  },
  {
    "id": "producto-102",
    "sourceNumber": 102,
    "section": "Carta de Bebidas",
    "category": "Bebidas Alcohólicas",
    "name": "Victoria Latón",
    "description": "Bebidas Alcohólicas · Victoria",
    "price": 40,
    "imageKind": "beer",
    "available": true,
    "sortOrder": 102
  },
  {
    "id": "producto-103",
    "sourceNumber": 103,
    "section": "Carta de Bebidas",
    "category": "Bebidas Alcohólicas",
    "name": "Modelo Latón",
    "description": "Bebidas Alcohólicas · Victoria",
    "price": 40,
    "imageKind": "beer",
    "available": true,
    "sortOrder": 103
  },
  {
    "id": "producto-104",
    "sourceNumber": 104,
    "section": "Carta de Bebidas",
    "category": "Bebidas Alcohólicas",
    "name": "Bebidas Alcohólicas",
    "description": "Jerez",
    "price": 40,
    "imageKind": "beer",
    "available": true,
    "sortOrder": 104
  }
]

